#!/bin/bash
set -v

docker ps -a -q -f status=exited | xargs --no-run-if-empty docker rm -v
docker images -f "dangling=true" -q | xargs --no-run-if-empty docker rmi
docker volume ls -qf dangling=true | xargs --no-run-if-empty docker volume rm
